import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { createApp, initDatabase } from "../lib/app.js";
import { testDatabase } from "./database.js";
test("Existing data, migration, complete ticket lifecycle, privacy and filters", async t => {
  const pool = await testDatabase();
  t.after(() => pool.end());
  await pool.query(await readFile(new URL("../sql/init.sql", import.meta.url), "utf8"));
  await pool.query("INSERT INTO tickets(reference,name,phone,service,description,priority,status) VALUES('TK-LEGACY-ABCD','Cliente anterior','600000000','Diagnóstico previo','Incidencia anterior','Normal','Contactado')");
  await pool.query("INSERT INTO ticket_notes(ticket_id,note) VALUES(1,'Nota antigua privada')");
  await initDatabase(pool);
  await initDatabase(pool);
  assert.equal((await pool.query("SELECT * FROM tickets")).rows[0].status, "Contactado");
  assert.equal((await pool.query("SELECT * FROM ticket_notes")).rows.length, 1);
  assert.equal((await pool.query("SELECT * FROM ticket_events")).rows.length, 1);
  const deliveries = [];
  let time = new Date("2026-09-21T10:00:00Z");
  const env = { ADMIN_PASSWORD: "test-password-only", SESSION_SECRET: "test-secret-only", TELEGRAM_BOT_TOKEN: "test-token", TELEGRAM_CHAT_ID: "test-chat" };
  const app = createApp({ pool, env, onError: error => console.error("test-only:", error.message), now: () => time, send: async (_url, options) => { deliveries.push(JSON.parse(options.body)); return { ok: true }; } });
  const server = app.listen(0, "127.0.0.1");
  await new Promise(resolve => server.once("listening", resolve));
  t.after(() => new Promise(resolve => server.close(resolve)));
  const base = "http://127.0.0.1:" + server.address().port;
  for (const route of ["/", "/admin", "/aviso-legal", "/terminos", "/privacidad", "/styles.css", "/legal.js"]) {
    const page = await fetch(base + route);
    assert.equal(page.status, 200, route + ": " + await page.text());
  }
  let cookie = "";
  async function request(path, method = "GET", body, auth = false) {
    const response = await fetch(base + path, { method, headers: { "content-type": "application/json", ...(auth ? { cookie } : {}) }, ...(body ? { body: JSON.stringify(body) } : {}) });
    const json = await response.json();
    return { status: response.status, json, response };
  }
  const config = (await request("/api/config")).json;
  assert.equal(JSON.stringify(config).includes("test-secret"), false);
  for (const route of ["/api/admin/tickets", "/api/admin/metrics", "/api/admin/tickets/1/notes"]) assert.equal((await request(route)).status, 401);
  const legacy = (await request("/api/tickets/status/TK-LEGACY-ABCD")).json;
  assert.equal(legacy.ticket.statusLabel, "En espera");
  assert.equal(legacy.history[0].kind, "snapshot");
  assert.equal(JSON.stringify(legacy).includes("Nota antigua"), false);
  const body = { name: "Persona Prueba", phone: "611222333", email: "prueba@example.com", service: config.services[0], category: config.categories[0], device: config.devices[0], priority: "Urgente", description: "Mi ordenador no funciona desde ayer.", privacyVersion: config.privacyVersion };
  assert.equal((await request("/api/tickets", "POST", { ...body, category: "inventada" })).status, 400);
  assert.equal((await request("/api/tickets", "POST", { ...body, email: "mal formado" })).status, 400);
  assert.equal((await request("/api/tickets", "POST", { ...body, urgencyRequested: true })).status, 409);
  assert.equal((await request("/api/tickets", "POST", { ...body, urgencyRequested: true, urgencyAccepted: true, urgencyFeeCents: 1 })).status, 409);
  const created = await request("/api/tickets", "POST", { ...body, urgencyRequested: true, urgencyAccepted: true, urgencyFeeCents: 1000 });
  assert.equal(created.status, 201);
  assert.equal(created.json.urgencyFeeCents, 1000);
  const reference = created.json.reference;
  assert.match(reference, /^TK-[A-Z0-9]+-[A-F0-9]{24}$/);
  assert.equal(deliveries.length, 1);
  for (const personal of [body.name, body.phone, body.email, body.description]) assert.equal(deliveries[0].text.includes(personal), false);
  assert.ok(deliveries[0].text.includes(reference));
  const login = await request("/api/admin/login", "POST", { password: env.ADMIN_PASSWORD });
  assert.equal(login.status, 200); cookie = login.response.headers.get("set-cookie").split(";")[0];
  assert.ok(login.response.headers.get("set-cookie").includes("HttpOnly"));
  assert.equal((await request("/api/admin/login", "POST", { password: "wrong" })).status, 401);
  const listed = await request("/api/admin/tickets?status=all&priority=Urgente&urgency=yes", "GET", undefined, true);
  assert.equal(listed.status, 200);
  assert.equal(listed.json.tickets.length, 1);
  const id = listed.json.tickets[0].id;
  assert.equal(listed.json.tickets[0].category, body.category);
  assert.equal((await request("/api/admin/tickets/" + id, "PATCH", { status: "Cerrado" })).status, 401);
  assert.equal((await request("/api/admin/tickets/" + id + "/notes", "POST", { note: "Detalle interno secreto" }, true)).status, 201);
  for (const status of ["Contactado", "En curso", "Esperando respuesta", "Resuelto", "Cerrado"]) {
    const updated = await request("/api/admin/tickets/" + id, "PATCH", { status }, true);
    assert.equal(updated.status, 200);
  }
  await request("/api/admin/tickets/" + id, "PATCH", { status: "Cerrado" }, true);
  const tracked = (await request("/api/tickets/status/" + reference)).json;
  assert.equal(tracked.ticket.statusLabel, "Cerrado");
  assert.equal(tracked.history.length, 6);
  for (const hidden of [body.name, body.phone, body.email, body.description, "Detalle interno secreto"]) assert.equal(JSON.stringify(tracked).includes(hidden), false);
  assert.equal((await request("/api/admin/tickets?status=active", "GET", undefined, true)).json.tickets.length, 1);
  assert.equal((await request("/api/admin/tickets?status=all&urgency=no", "GET", undefined, true)).json.tickets.length, 1);
  const metrics = (await request("/api/admin/metrics", "GET", undefined, true)).json.metrics;
  assert.deepEqual(metrics, { total: 2, pending: 1, urgent: 0, resolved: 0, closed: 1 });
  time = new Date("2026-09-19T09:00:00Z");
  assert.equal((await request("/api/tickets", "POST", { ...body, urgencyRequested: true, urgencyAccepted: true, urgencyFeeCents: 1000 })).status, 409);
  const oldClient = { name: body.name, phone: body.phone, service: body.service, description: body.description, priority: "Urgente" };
  const normal = await request("/api/tickets", "POST", oldClient);
  assert.equal(normal.status, 201); assert.equal(normal.json.urgencyFeeCents, 0);
  assert.equal((await request("/api/tickets/status/123")).status, 400);
  assert.equal((await request("/api/tickets/status/TK-MISSING-ABCD")).status, 404);
  assert.equal((await request("/api/admin/tickets/99999", "PATCH", { status: "Resuelto" }, true)).status, 404);
  assert.equal((await request("/api/admin/tickets?urgency=invalid", "GET", undefined, true)).status, 400);
  const logout = await request("/api/admin/logout", "POST");
  assert.ok(logout.response.headers.get("set-cookie").includes("Expires="));
});
